SUSE/klp-build

- klpbuild/ibs.py
- klpbuild/ksrc.py
ksrc.py: Add cve/linux-5.14-LTSS branch as a primary branch receiving CVE fixes for 5.14 based kernels
ibs.py: Allow to build LP without having a directory with expected bsc# to support LPs extending already existing ones
> Add new cve branch and allow LPs extending existing ones without changing the original LP's name

- klpbuild/templ.py
Without this header the KLP_RELOC_SYMBOL macro won't be recognized.
> templ.py: Include linux/livepatch.h header for IBT enabled kernels

- klpbuild/cmd.py
- klpbuild/setup.py
- tests/test_extract.py
- tests/test_setup.py
- tests/test_templ.py
--filter exists for a long time, so it's time to retire --codestreams.
> setup: Remove --codestreams in favor of --filter

- klpbuild/cmd.py
- klpbuild/codestream.py
- klpbuild/config.py
- klpbuild/extractor.py
- klpbuild/ibs.py
- klpbuild/inline.py
- klpbuild/ksrc.py
- klpbuild/setup.py
- klpbuild/templ.py
- klpbuild/utils.py
- tests/test_config.py
- tests/test_ksrc.py
- tests/test_setup.py
- tests/test_utils.py
- tests/utils.py
With this PR we are mostly done: a ton of things now are moved into util and Codestream classes
> No config - move even more things out of Config class

- klpbuild/codestream.py
- klpbuild/config.py
- klpbuild/extractor.py
- klpbuild/ksrc.py
This can happen when the extraction process is interrupted, resulting in missing kernel files.
> extractor: Check if make invocation fails

- klpbuild/cmd.py
Fixes: 85d3a8e ("setup: Move ctor args into a functions")
> cmd: use correct archs field

- klpbuild/setup.py
We don't need to assign archs back aftert sorting, since sort() returns None.
> setup: Do not reassign archs with archs.sort()

- klpbuild/ibs.py
- klpbuild/utils.py
Until now it was required to the developer to always base the branch on top of one of branches assigned to the codestreams. As the number of base branches increase, it's easier if klp-build could make it automatically.
From now on, it's expected that the bscXXXXXX branch is based on the kgraft-patches' master branch, which doesn't include any code, since klp-build will clone that branch, and rebase it on top of a base branch related to the codestream affected.
For example, for 12.5 codestreams, it will get the branch for bscXXXXX_12.5uXXX (which should contain only the directory for the bscXXX) and rebase on top of origin/master-livepatch-sle12.
Hopefully this change will make the LP developers to check less details when creating a livepatch.
> ibs: push: Get the codestream branch and rebase it on top of base branch

- klpbuild/setup.py
- tests/test_templ.py
Also, fix the problematic test that was checking a condition that was only being triggered if only one arch was set, but was using all archs wrongly.
> setup: Always set archs and cve to cs_data

- klpbuild/klplib/codestream.py
- klpbuild/klplib/ibs.py
- klpbuild/klplib/ksrc.py
- klpbuild/klplib/supported.py
- klpbuild/klplib/templ.py
- klpbuild/klplib/utils.py
- klpbuild/main.py
- klpbuild/plugins/extractor.py
- klpbuild/plugins/setup.py
- tests/test_codestream.py
- tests/test_ksrc.py
Before this patch, executing the `scan` command would create a livepatch working directory, even though it should not setup any workspace (which is instead done by the `setup` command).
There are two reasons behind this misbheavior:
1.  `scan` is a method of the `GitHelper` class, which includes `lp_name` as one of its fields. While this fiels is irrelevant for scan, it was still required, forcing us to provide a dummy value just to instantiate the GitHelper object. See `main.py`:
```py
elif args.cmd == "scan":
GitHelper("bsc_check", "", "").scan(args.cve, args.conf, False)
```
Here, `bsc_check` was used as a placeholder `lp_name` just to allow instantiation.
2. `scan` relied on `get_commits` (the function behind the `get-patches` command), which did more than just retrieving fixes and …
> Drop bsc_check from scan

- klpbuild/klplib/cmd.py
- klpbuild/klplib/ksrc.py
- klpbuild/klplib/plugins.py
- klpbuild/main.py
- klpbuild/plugins/scan.py
- klpbuild/plugins/setup.py
- tests/test_ksrc.py
- tests/test_scan.py
This Pull Request introduces the first version of a plugin system, aiming to modularize all commands into standalone plugins.
A plugin is nothing else than just a module in the package `klpbuild.plugins` that exposes (at least) two functions:
1. `register_argparser()` : 
- This function registers the plugin’s command-line arguments.
- Get the parent parser in the arguments and should add a subparser to it.
3. `run()` : 
- This function executes the plugin's logic.
-  It should accept arguments that were registered using the above function `register_argparser()`
e.g.:
```python3
def run(lp_name, lp_filter):
pass
```
When introducing a plugin, there's no need to modify `klpbuild/main.py` as the plugins are detected at runtime if they have the above mentioned `run` function.
Here’s how the …
> Introduce plugin system

- klpbuild/main.py
The except clause was introduced to catch assertion errors raised during the stage in charge of loading the plugins and skip those not yet converted so they can use the old machinery.
This can catch every type of assertion error, causing silent exit of the plugins loaded here in case they raise any other assertion error.
Hence filter the only assertion error caused during the loading and re raise all the others.
When all the modules get converted into plugins we should just drop this code and don't catch anything.
fixes: 60725569 ("klplib: plugins: add helper to dynamically load plugins")
> Stop catching every assertion error

- klp-build.1
- klpbuild/klplib/cmd.py
- klpbuild/klplib/config.py
- klpbuild/klplib/ksrc.py
- klpbuild/main.py
I believe it's useful to have a global option to enable/disable debugging logs.
I open this a Draft PR so that if you have any other logging call site that would like to convert from `logging.info` to `logging.debug` we can do it in this PR and then merge it.
For instance, I propose to change it when loading the `config` file.
> Add verbose global option

- klpbuild/klplib/cmd.py
- klpbuild/main.py
- klpbuild/plugins/setup.py
- tests/test_extract.py
- tests/test_ibs.py
- tests/test_setup.py
- tests/test_templ.py
Hi, another command converted to the plugin system.
There's no functional change, just moving code around.
I also converted all related tests and carefully verified their correctness, as the process was error-prone. Let me know if you spot anything I might have missed!
> Convert setup to plugins

- klpbuild/plugins/extractor.py
- tests/test_extract.py
Our make strategy worked well until we found the a new way of getting the gcc arguments used to compile a kernel source file. Recently it started to fail on newer codestreams, failing to find the proper _source_ directory from the -obj directory.
Use this opportunity to finally implement the arguments finding using compile_commands.json that is packaged by kernel-livepatch-default-livepatch-devel rpm.
The paths are extactly the same being found using make, but the instead of the absolute paths to the source directory of the codestreams, the compile_commands.json used '../'. Replacing ../ by the source directory of the affected codestream fixes the problem.
> extract: Get gcc args by using compile_commands.json

- klpbuild/klplib/ibs.py
klp-build setup does not decompress vmlinux and config files from s390 rpms.
The problem is that cs.get_boot_file() returns x86_64 path by default. Fix it by explicitly passing the arch parameter.
> ibs: Fix decompression of vmlinux and config for s390x

- klpbuild/plugins/scan.py
The packages for all code streams are currently downloaded and decompressed even when the caller is interested only into a particular one.
As a result, "klp-build setup" command runs much longer it could. It is not good in production and it makes debugging really painful.
The missing data are collected in scan(). Ignore the filtered code streams there.
IMPORTANT: I am not completely sure that it does not break some workflow. But the following
command succeeded with this change and was much faster:
klp-build -v setup --filter 15.3u42 --cve 2024-56600 --name bsc1235218 --conf CONFIG_IPV6 --file-func net/ipv6/af_inet6.c inet6_create
> scan: Ignore code streams which do not match --filter

- klpbuild/klplib/codestream.py
- klpbuild/klplib/data.py
- klpbuild/klplib/ibs.py
- klpbuild/plugins/data.py
- klpbuild/plugins/scan.py
- klpbuild/plugins/setup.py
- tests/test_scan.py
The rpms can now be downloaded using the following command instead of having to necessarily run  `setup`:
- `klp-build data --download_missing` to download all the missing codestream data for the supported codestreams;
- `klp-build data --download_force` to force the download even if specific codestreams data are present, in case they got corrupted;
Both the command can be used with `--filter` option.
Nevertheless, although this approach removes the chicken and egg problem, it's still not optimal to download all the missing data for *all* the supported codestreams for anyone who's not a livepatching developer as it will take too much space on disk. So I thought that adding a `--download_data` option to the `scan` command would also solve the problem, as it would download only the data for …
> Improve rpms handling

- klpbuild/plugins/extractor.py
- tests/test_extract.py
If the function to livepatch has an optimization clone, all its callers should be livepatched as well to avoid any of this clones from being left unpatched. Emit a warning when hitting this corner case.
We can merge this when the new version of `klp-ccp` using the ipa-clones gets released.
> Emit warning when optimization clones are found

- setup.py
importlib is part of python3, and leaving this depency here makes it fail to be installed on openSUSE Tumbleweed.
> setup.py: Remove importlib as dependency

- klpbuild/klplib/utils.py
PurePath doesn't have is_file(), so prepare-test fails when the test script is contained in a directory
> klplib: utils: don't use PurePath in get_tests_path

- klpbuild/klplib/kernel_tree.py
- klpbuild/plugins/extractor.py
- klpbuild/plugins/scan.py
So we don't have to remember every time we use the kernel tree in a new part of the codebase :)
> klplib: kernel_tree: use decorator to update kernel tree tags

- klpbuild/klplib/ksrc.py
- klpbuild/plugins/scan.py
This refactoring is in preparation to introduce a way to read the config of a specific codestream directly from the kernel source git repository, as proposed [here](https://github.com/SUSE/klp-build/pull/110#discussion_r2042589514).
> ksrc refactoring

- klpbuild/klplib/codestream.py
- klpbuild/klplib/ksrc.py
This PR is a prerequisite for #110 .
Please @fgyanz , notice that I have copied the `read_file_in_tag` function from you PR and moved in `klplib/utils` so that it can be used both from `ksrc` and `kernel_tree`.
> klplib: codestream: use ksrc to read config

- klpbuild/plugins/extractor.py
Again klp-ccp is too slow to keep up with the gcc flags used by "modern" kernels, so we need to do something on our side, otherwise we can't produce livepatches.
> -Wno-dangling-pointer removal

- klpbuild/klplib/ibs.py
This is needed otherwise it will fail whenever we need to download any rpms on setup phase.
> klplib: ibs: Fix download_and_extract new tuple element

- klpbuild/klplib/codestream.py
- klpbuild/klplib/codestreams_data.py
- klpbuild/klplib/ibs.py
- klpbuild/klplib/ksrc.py
- klpbuild/klplib/patch.py
- klpbuild/klplib/supported.py
- klpbuild/klplib/templ.py
- klpbuild/klplib/utils.py
- klpbuild/plugins/cs_diff.py
- klpbuild/plugins/extract.py
- klpbuild/plugins/log.py
- klpbuild/plugins/prepare_tests.py
- klpbuild/plugins/push.py
- klpbuild/plugins/scan.py
- klpbuild/plugins/setup.py
- tests/test_codestream.py
- tests/test_config.py
- tests/test_utils.py
This pull request was to refactor the `Codestream` class, but as a side effect I also cleaned other portions of the code.
There are no logical changes, it's mostly about dropping unneeded fields in favor of methods.
I modified the constructor of the `Codestream` class so that we can avoid dealing with random string like `"12.5rtu4"` but rather use the appropriate class with its functions, like:
```py
cs = Codestream("12.5rtu4")
cs.get_config_content()
```
Also, I dropped `no_check` from `scan` as it was anyway not used and it didn't make sense to have it.
I am opening this PR as Draft as I haven't yet fully reviewed it and still depends on #140 .
> Refactor codestream
